### ISSUE TITLE
The cloud_data generation

### ISSUE THREAD

**Issue by yjj-liwei** [wuchangsheng951/GLNET#1]
Hello, Could you please provide the code for cloud image generation for the entire dataset? Such as AID, NWPU-RESISC45.
Have a nice day!

**Comment by HMS97** [comment]
Hello, the code for cloud generation is provided in the repo. Please see [cloud_generation.py](https://github.com/wuchangsheng951/GLNET/blob/main/cloud_generation.py). As for the  AID, NWPU-RESISC45, I don't have them. I'm using the RSSCN7 dataset.
