### ISSUE TITLE
Cloud_data

### ISSUE THREAD

**Issue by yjj-liwei** [wuchangsheng951/GLNET#2]
Hello, I have generated clouds on the UCM dataset using your code for cloud generation, but the generated image has changed rather drastically in colour compared to the original image. Could you help me?
![sparseresidential00](https://user-images.githubusercontent.com/73466929/230530703-7d0768e9-4b78-468f-99e9-965d2e4ac22c.jpg)
![sparseresidential00](https://user-images.githubusercontent.com/73466929/230530846-b5ecb4b9-d8e8-4de8-aa45-fa635400379f.png)

**Comment by HMS97** [comment]
It seems like you read the image in BGR format rather than RGB. You could have a look.
